name: telegram_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  intl_phone_field: # https://github.com/animeshxd/intl_phone_field
    path: intl_phone_field
  nested: ^1.0.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  tdffi: # https://github.com/animeshxd/tdffi-dev
    path: tdffi 

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
