name: telegram_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  go_router: ^10.1.2
  humanizer: ^2.2.0
  intl: ^0.18.1
  intl_phone_field:
    git: https://github.com/animeshxd/intl_phone_field
  logging: ^1.2.0
  nested: ^1.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  tdffi:
    path: tdffi

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/test.jpg
